package com.g41.trashsmart_server.Enums;

public enum OrgType {
    EDUCATION,
    HEALTH,
    SOCIAL_SERVICES,
    GOVERNMENT,
    BUSINESS_AND_COMMERCE,
    TECHNOLOGY,
    ENVIRONMENT,
    ARTS_AND_CULTURE,
    MEDIA_AND_COMMUNICATION,
    TRANSPORTATION,
    AGRICULTURE_AND_FOOD,
    FINANCE,
    CONSTRUCTION_AND_REAL_ESTATE,
    TOURISM_AND_HOSPITALITY,
    ENERGY
}
